### ISSUE TITLE
Wizard's code-source

### ISSUE THREAD

**Issue by FKSI** [4lejandrito/creepyface#3]
Hello, 

Anychance to have Wizard's source code? :)

**Comment by 4lejandrito** [comment]
Hi @FKSI,

I am planning to open source the whole website but I still need to work a bit on it to make it public. What is exactly what you are interested in? 

[This](https://gist.github.com/4lejandrito/c5382d78040130d26fb312721b9f846c) is the main modal and [this](https://gist.github.com/4lejandrito/38dccd5136ef84e773bb5e4c559c5851) is the video component used to take the pictures. 

Please let me know if you're curious about something else.

I'll let you know when I manage to get the whole site published.

**Comment by 4lejandrito** [comment]
I'll close this issue for now. Thanks!

**Comment by FKSI** [comment]
Hi, 

Apologize for the late reply, actually I'm interesting to leverage your app and add a Face Tracking module instead of the mouse cursor trigger :)

**Comment by 4lejandrito** [comment]
Hi @FKSI,

No worries. 

So if I understood you correctly, instead of having the picture look at the mouse pointer you want to define your own logic based on some face tracking algorithm. Am I right?

If that is correct, I think you will find [this documentation](https://github.com/4lejandrito/creepyface#super-advanced-usage) useful. Those are instructions on how to define a custom point source. 

Please let me know if that helps. 

I am looking forward to seeing what you build!

Thanks!

**Comment by FKSI** [comment]
Oh yes indeed :)! I will probably get to it after xmas break!
